/**
 * SCAFFOLD DRAFT — Ch.6 forged boss draft(s) (generated by `npm run scaffold -- ch6`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch6/checklist.md. Edit freely; re-running overwrites this tree.
 */
import { DRAFT_BOSS_SCRIPTS } from '../bosses';
import type { BossScriptDef } from '../../../schemas';

/** the forged boss draft(s) for Ch.6, from their templates (src/levelkit/forge/
 *  bosses.ts). Promote: move into src/data/bosses.ts + rewrite every *_draft
 *  dialogue id into a real §A11 line + register FORM_ART for any suffixed form. */
export const CH6_BOSS_DRAFTS: BossScriptDef[] = [
  DRAFT_BOSS_SCRIPTS.laughing_sphinx,
];
