/**
 * SCAFFOLD DRAFT — Ch.6 dungeon grammar (site 'laughing_ruins') (generated by `npm run scaffold -- ch6`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch6/checklist.md. Edit freely; re-running overwrites this tree.
 */
import type { DungeonRecipe, DraftMapDef } from '../../../schemas';
import { buildDungeon } from '../../../levelkit/dungeons';

/** the dungeon-grammar draft for "The Laughing Ruins → the Sphinx’s chin". (recipe + seed → identical
 *  bytes; Prime Law 2). Promote: hand-art skin, name the rooms, place the boss door. */
export const CH6_DUNGEON_RECIPE: DungeonRecipe = {kind: "dungeon", id: "laughing_ruins", seed: 1607393786, site: "laughing_ruins", encounterBand: "ch6"};

/** build the dungeon draft on demand (the LEVELKIT LAB walks it; bench:map sizes it) */
export const buildCh6Dungeon = (): DraftMapDef => buildDungeon(CH6_DUNGEON_RECIPE);
