/**
 * SCAFFOLD DRAFT — Ch.6 The Ruins That Laugh — draft tree barrel (generated by `npm run scaffold -- ch6`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch6/checklist.md. Edit freely; re-running overwrites this tree.
 */
export { CH6_DUNGEON_RECIPE, buildCh6Dungeon } from './dungeon';
export { CH6_SETTLEMENT_RECIPES, ch6Settlements } from './settlements';
export { CH6_ROSTER } from './roster';
export { CH6_BOSS_DRAFTS } from './boss';
