/**
 * SCAFFOLD DRAFT — Ch.6 settlement recipes (generated by `npm run scaffold -- ch6`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch6/checklist.md. Edit freely; re-running overwrites this tree.
 */
import type { Recipe } from '../../../schemas';
import { generate } from '../../../levelkit';
import type { DraftMapDef } from '../../../schemas';

/** the §A5 settlements of Ch.6, as forge recipes. Promote: hand-build the
 *  landmarks + write the §A11 NPC dialogue, then drop the role-tagged slots. */
export const CH6_SETTLEMENT_RECIPES: Recipe[] = [
  {kind: "city", id: "zanzibel", seed: 2231469530, style: "bazaar-port", size: [48, 32], districts: ["market", "civic"], encounterBand: "ch6"},
];

/** build every settlement draft on demand (deterministic on each recipe's seed) */
export const ch6Settlements = (): DraftMapDef[] => CH6_SETTLEMENT_RECIPES.map(generate);
