/**
 * SCAFFOLD DRAFT — Ch.7 dungeon grammar (site 'night_train') (generated by `npm run scaffold -- ch7`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch7/checklist.md. Edit freely; re-running overwrites this tree.
 */
import type { DungeonRecipe, DraftMapDef } from '../../../schemas';
import { buildDungeon } from '../../../levelkit/dungeons';

/** the dungeon-grammar draft for "The Night Train → palace throne". (recipe + seed → identical
 *  bytes; Prime Law 2). Promote: hand-art skin, name the rooms, place the boss door. */
export const CH7_DUNGEON_RECIPE: DungeonRecipe = {kind: "dungeon", id: "night_train", seed: 3897208087, site: "night_train", encounterBand: "ch7", rooms: 5};

/** build the dungeon draft on demand (the LEVELKIT LAB walks it; bench:map sizes it) */
export const buildCh7Dungeon = (): DraftMapDef => buildDungeon(CH7_DUNGEON_RECIPE);
