/**
 * SCAFFOLD DRAFT — Ch.7 The Cobra's Palace — draft tree barrel (generated by `npm run scaffold -- ch7`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch7/checklist.md. Edit freely; re-running overwrites this tree.
 */
export { CH7_DUNGEON_RECIPE, buildCh7Dungeon } from './dungeon';
export { CH7_SETTLEMENT_RECIPES, ch7Settlements } from './settlements';
export { CH7_ROSTER } from './roster';
export { CH7_BOSS_DRAFTS } from './boss';
