/**
 * SCAFFOLD DRAFT — Ch.7 settlement recipes (generated by `npm run scaffold -- ch7`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch7/checklist.md. Edit freely; re-running overwrites this tree.
 */
import type { Recipe } from '../../../schemas';
import { generate } from '../../../levelkit';
import type { DraftMapDef } from '../../../schemas';

/** the §A5 settlements of Ch.7, as forge recipes. Promote: hand-build the
 *  landmarks + write the §A11 NPC dialogue, then drop the role-tagged slots. */
export const CH7_SETTLEMENT_RECIPES: Recipe[] = [
  {kind: "city", id: "chandrapore", seed: 987496185, style: "bazaar-port", size: [48, 32], districts: ["market", "civic"], encounterBand: "ch7"},
];

/** build every settlement draft on demand (deterministic on each recipe's seed) */
export const ch7Settlements = (): DraftMapDef[] => CH7_SETTLEMENT_RECIPES.map(generate);
