/**
 * THE CHAPTER SCAFFOLD — the plan (S15g Movement Four, ADR-047). Pure: a
 * ChapterManifest in, a deterministic list of FILES out. tools/chapter-scaffold.ts
 * is the thin fs wrapper that writes them; this is the library the vitest pins
 * (the mapcheck/pressure precedent — the math is pure + tested, the tool owns IO).
 *
 * (manifest → identical files forever): seeds derive from a pure FNV-1a over the
 * id, never a clock — Date.now()/Math.random() never appear under src/levelkit/**
 * (Prime Law 2). The emitted tree is DRAFTS (Prime Law 1): it lands under
 * src/data/drafts/chN/**, re-exports the forge's roster + boss draft + a dungeon
 * recipe, and is EXCLUDED from MAPS / the canon manifests / the §B4 sweep exactly
 * like every draft. Promotion is a human act; the checklist tells the session how.
 */
import type { ChapterManifest, DungeonRecipe, Recipe, SettlementStyle } from '../schemas';

export interface ScaffoldFile {
  /** repo-relative path (forward slashes) */
  path: string;
  content: string;
}

export interface ScaffoldPlan {
  chapter: number;
  /** the complete draft tree + the checklist, in write order */
  files: ScaffoldFile[];
  /** the dungeon-grammar recipe (null for a bespoke, site-less dungeon) */
  dungeonRecipe: DungeonRecipe | null;
  /** one recipe per §A5 settlement */
  settlementRecipes: Recipe[];
  /** the forged boss-draft ids the tree re-exports (bespoke bosses excluded) */
  bossDraftIds: string[];
  /** the human-readable lines the tool prints */
  summary: string[];
}

/** FNV-1a over a string → an unsigned 32-bit seed (the levelkit.test fnv, on a
 *  string key): pure, stable across boots forever (Prime Law 2). */
function seedFor(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** the draft size each settlement kind opens at (the session grows it) */
const SETTLEMENT_SIZE: Record<'city' | 'town' | 'village', [number, number]> = {
  city: [48, 32],
  town: [40, 28],
  village: [28, 22],
};

/** derive the §A5 settlement recipes from the manifest (deterministic seeds) */
function settlementRecipesFor(m: ChapterManifest): Recipe[] {
  return m.settlements.map((s) => {
    const seed = seedFor(`${m.chapter}:${s.id}`);
    const size = SETTLEMENT_SIZE[s.kind];
    const style: SettlementStyle = s.style ?? 'americana';
    if (s.kind === 'city') {
      return { kind: 'city', id: s.id, seed, style, size, districts: ['market', 'civic'], encounterBand: m.band };
    }
    if (s.kind === 'town') {
      return { kind: 'town', id: s.id, seed, style, size, lanes: 3, encounterBand: m.band };
    }
    return { kind: 'village', id: s.id, seed, style, size, encounterBand: m.band };
  });
}

/** derive the dungeon-grammar recipe (null when the dungeon is bespoke/site-less) */
function dungeonRecipeFor(m: ChapterManifest): DungeonRecipe | null {
  const site = m.dungeon.site;
  if (!site) return null;
  const recipe: DungeonRecipe = {
    kind: 'dungeon',
    id: site,
    seed: seedFor(`${m.chapter}:${site}`),
    site,
    encounterBand: m.band,
  };
  // the night-train's car count is a §A6 pacing parameter (the ≤30-min law)
  if (site === 'night_train') recipe.rooms = 5;
  return recipe;
}

/** the forged boss-draft ids this chapter re-exports (bespoke bosses have none) */
function bossDraftIdsFor(m: ChapterManifest): string[] {
  const ids: string[] = [];
  if (m.boss.template !== 'bespoke') ids.push(m.boss.id);
  for (const mb of m.minibosses ?? []) if (mb.template !== 'bespoke') ids.push(mb.id);
  return ids;
}

const HEADER = (chapter: number, what: string): string =>
  `/**\n * SCAFFOLD DRAFT — Ch.${chapter} ${what} (generated by \`npm run scaffold -- ch${chapter}\`).\n` +
  ` * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /\n` +
  ` * the canon manifests / the §B4 sweep. Promotion is a human act — see\n` +
  ` * docs/chapters/ch${chapter}/checklist.md. Edit freely; re-running overwrites this tree.\n */\n`;

function dungeonFile(m: ChapterManifest, recipe: DungeonRecipe | null): string {
  const n = m.chapter;
  if (!recipe) {
    return (
      HEADER(n, 'dungeon (BESPOKE)') +
      `\n// Ch.${n}'s dungeon ("${m.dungeon.name}") is BESPOKE — shipped/frozen, not a\n` +
      `// forge grammar. There is no recipe to scaffold; promote by hand.\nexport {};\n`
    );
  }
  const lit = JSON.stringify(recipe).replace(/"(\w+)":/g, '$1: ').replace(/,/g, ', ');
  return (
    HEADER(n, `dungeon grammar (site '${recipe.site}')`) +
    `import type { DungeonRecipe, DraftMapDef } from '../../../schemas';\n` +
    `import { buildDungeon } from '../../../levelkit/dungeons';\n\n` +
    `/** the dungeon-grammar draft for "${m.dungeon.name}". (recipe + seed → identical\n` +
    ` *  bytes; Prime Law 2). Promote: hand-art skin, name the rooms, place the boss door. */\n` +
    `export const CH${n}_DUNGEON_RECIPE: DungeonRecipe = ${lit};\n\n` +
    `/** build the dungeon draft on demand (the LEVELKIT LAB walks it; bench:map sizes it) */\n` +
    `export const buildCh${n}Dungeon = (): DraftMapDef => buildDungeon(CH${n}_DUNGEON_RECIPE);\n`
  );
}

function settlementsFile(m: ChapterManifest, recipes: Recipe[]): string {
  const n = m.chapter;
  const lits = recipes
    .map((r) => '  ' + JSON.stringify(r).replace(/"(\w+)":/g, '$1: ').replace(/,/g, ', '))
    .join(',\n');
  return (
    HEADER(n, 'settlement recipes') +
    `import type { Recipe } from '../../../schemas';\n` +
    `import { generate } from '../../../levelkit';\nimport type { DraftMapDef } from '../../../schemas';\n\n` +
    `/** the §A5 settlements of Ch.${n}, as forge recipes. Promote: hand-build the\n` +
    ` *  landmarks + write the §A11 NPC dialogue, then drop the role-tagged slots. */\n` +
    `export const CH${n}_SETTLEMENT_RECIPES: Recipe[] = [\n${lits},\n];\n\n` +
    `/** build every settlement draft on demand (deterministic on each recipe's seed) */\n` +
    `export const ch${n}Settlements = (): DraftMapDef[] => CH${n}_SETTLEMENT_RECIPES.map(generate);\n`
  );
}

function rosterFile(m: ChapterManifest): string {
  const n = m.chapter;
  return (
    HEADER(n, 'forged enemy roster') +
    `import { FORGED_ROSTERS } from '../../../levelkit/forge/registry';\n` +
    `import type { DraftEnemyDef } from '../../../schemas';\n\n` +
    `/** the forged Ch.${n} roster (deterministic on FIXED_SEED[${n}] = ${1000 + n}). Promote:\n` +
    ` *  pick/redraw each face in the Sprite Lab, write §A11 names + death lines, move\n` +
    ` *  the stripped EnemyDefs into src/data/enemies.ts + extend the §A7 manifest. */\n` +
    `export const CH${n}_ROSTER: readonly DraftEnemyDef[] = FORGED_ROSTERS[${n}];\n`
  );
}

function bossFile(m: ChapterManifest, bossIds: string[]): string {
  const n = m.chapter;
  const rows = bossIds.map((id) => `  DRAFT_BOSS_SCRIPTS.${id},`).join('\n');
  const bespoke = m.boss.template === 'bespoke'
    ? `\n// ${m.boss.name} (${m.boss.id}) is BESPOKE — not one of the ten forge templates;\n` +
      `// it lands hand-built (the Tick / the Hush finale pattern), not from the forge.\n`
    : '';
  return (
    HEADER(n, 'forged boss draft(s)') +
    `import { DRAFT_BOSS_SCRIPTS } from '../bosses';\n` +
    `import type { BossScriptDef } from '../../../schemas';\n` +
    bespoke +
    `\n/** the forged boss draft(s) for Ch.${n}, from their templates (src/levelkit/forge/\n` +
    ` *  bosses.ts). Promote: move into src/data/bosses.ts + rewrite every *_draft\n` +
    ` *  dialogue id into a real §A11 line + register FORM_ART for any suffixed form. */\n` +
    `export const CH${n}_BOSS_DRAFTS: BossScriptDef[] = [\n${rows}${rows ? '\n' : ''}];\n`
  );
}

function indexFile(m: ChapterManifest, hasDungeon: boolean): string {
  const n = m.chapter;
  const dungeon = hasDungeon ? `export { CH${n}_DUNGEON_RECIPE, buildCh${n}Dungeon } from './dungeon';\n` : '';
  return (
    HEADER(n, `${m.title} — draft tree barrel`) +
    dungeon +
    `export { CH${n}_SETTLEMENT_RECIPES, ch${n}Settlements } from './settlements';\n` +
    `export { CH${n}_ROSTER } from './roster';\n` +
    `export { CH${n}_BOSS_DRAFTS } from './boss';\n`
  );
}

function checklist(m: ChapterManifest, plan: ScaffoldPlan): string {
  const n = m.chapter;
  const L: string[] = [];
  L.push(`# Ch.${n} — ${m.title} (${m.region}) — promotion checklist`);
  L.push('');
  L.push('> Generated by `npm run scaffold -- ch' + n + '` (ADR-047). The forge built the');
  L.push('> boring 60%; this chapter session spends itself on the SOUL. Promotion is a');
  L.push('> human act (Prime Law 1) — drafts under `src/data/drafts/ch' + n + '/` are dev-only.');
  L.push('');
  L.push('## The chapter at a glance (from the manifest)');
  L.push('');
  L.push(`- **Region / travel-in:** ${m.region}${m.travel ? ` · ${m.travel}` : ' · on foot'}`);
  L.push(`- **Target end level:** ${m.targetLevel} · **roster band:** \`${m.band}\``);
  L.push(`- **Ember #${m.ember}**${m.heartlight ? ` — Heartlight "${m.heartlight}"` : ''}`);
  L.push(`- **Dungeon:** ${m.dungeon.name}${m.dungeon.site ? ` (grammar \`${m.dungeon.site}\`)` : ' (bespoke)'}`);
  L.push(`- **Boss:** ${m.boss.name} (\`${m.boss.id}\`, ${m.boss.hp} HP, template \`${m.boss.template}\`)`);
  for (const mb of m.minibosses ?? []) L.push(`  - **Miniboss:** ${mb.name} (\`${mb.id}\`, ${mb.hp} HP, \`${mb.template}\`)`);
  L.push(`- **Settlements:** ${m.settlements.map((s) => `${s.id} (${s.kind})`).join(', ')}`);
  L.push('');
  L.push('## Promote the draft tree');
  L.push('');
  if (plan.dungeonRecipe) {
    L.push(`- [ ] **Dungeon** — walk \`CH${n}_DUNGEON_RECIPE\` in the LEVELKIT LAB; reskin with`);
    L.push(`      hand art (ADR-020), name the rooms in §A11 voice, place the boss-trigger door.`);
  } else {
    L.push(`- [ ] **Dungeon** — bespoke ("${m.dungeon.name}"); hand-build, no recipe to promote.`);
  }
  L.push(`- [ ] **Roster** — \`CH${n}_ROSTER\` (${plan.bossDraftIds.length ? 'forged' : 'forged'}): pick/redraw each face in the Sprite Lab,`);
  L.push(`      write §A11 names + death lines, expand to the §A7 twenty, then move the`);
  L.push(`      stripped \`EnemyDef\`s into \`src/data/enemies.ts\` and extend the §A7 manifest.`);
  for (const id of plan.bossDraftIds) {
    L.push(`- [ ] **Boss \`${id}\`** — rewrite its \`*_draft\` dialogue ids into real §A11 lines,`);
    L.push(`      register \`FORM_ART\` for any suffixed form, move it into \`src/data/bosses.ts\`.`);
  }
  if (m.boss.template === 'bespoke') {
    L.push(`- [ ] **Boss \`${m.boss.id}\`** — bespoke (${m.boss.name}); hand-build like the Tick/Hush.`);
  }
  for (const s of m.settlements) {
    L.push(`- [ ] **Settlement \`${s.id}\`** (${s.kind}) — build the landmarks, write the NPC`);
    L.push(`      dialogue + shops, drop the role-tagged draft slots, tag \`settlement: '${s.kind}'\`.`);
  }
  L.push(`- [ ] **Quests** — author the five §A10 quests (the named core: ${m.quests.map((q) => `\`${q}\``).join(', ')});`);
  L.push(`      each adds/strengthens a finale CALLER. Wire them into \`src/data/quests.ts\`.`);
  L.push('');
  L.push('## Land the chapter (the S14c flip)');
  L.push('');
  L.push(`- [ ] Flip \`CHAPTER_MANIFESTS['${n}'].status\` to \`'shipped'\` and fill in the LIVE`);
  L.push(`      \`maps\` + \`dungeon.maps\` + \`quests\` — the validator's live assertions switch on.`);
  L.push(`- [ ] \`npm test\` (tsc + validate + vitest) green; append the chapter's ADR.`);
  L.push('');
  return L.join('\n');
}

/**
 * Build the complete draft tree for a chapter: the dungeon-grammar recipe, the
 * forged roster re-export, the forged boss draft(s), the settlement recipes, a
 * barrel, and a promotion checklist. Pure + deterministic — same manifest, same
 * files, forever. The tool writes `files`; the test pins them.
 */
export function scaffoldChapter(m: ChapterManifest): ScaffoldPlan {
  const dungeonRecipe = dungeonRecipeFor(m);
  const settlementRecipes = settlementRecipesFor(m);
  const bossDraftIds = bossDraftIdsFor(m);
  const base = `src/data/drafts/ch${m.chapter}`;

  const plan: ScaffoldPlan = {
    chapter: m.chapter,
    files: [],
    dungeonRecipe,
    settlementRecipes,
    bossDraftIds,
    summary: [],
  };

  plan.files = [
    { path: `${base}/dungeon.ts`, content: dungeonFile(m, dungeonRecipe) },
    { path: `${base}/settlements.ts`, content: settlementsFile(m, settlementRecipes) },
    { path: `${base}/roster.ts`, content: rosterFile(m) },
    { path: `${base}/boss.ts`, content: bossFile(m, bossDraftIds) },
    { path: `${base}/index.ts`, content: indexFile(m, dungeonRecipe !== null) },
    { path: `docs/chapters/ch${m.chapter}/checklist.md`, content: checklist(m, plan) },
  ];

  plan.summary = [
    `Ch.${m.chapter} — ${m.title} (${m.region}), band ${m.band}, target L${m.targetLevel}`,
    `  dungeon : ${dungeonRecipe ? `${dungeonRecipe.site} (seed ${dungeonRecipe.seed})` : `${m.dungeon.name} (bespoke — no recipe)`}`,
    `  roster  : CH${m.chapter}_ROSTER → FORGED_ROSTERS[${m.chapter}] (forged, deterministic)`,
    `  boss    : ${bossDraftIds.length ? bossDraftIds.join(', ') : `${m.boss.id} (bespoke)`}`,
    `  towns   : ${settlementRecipes.map((r) => r.id).join(', ')}`,
    `  ${plan.files.length} files → ${base}/** + docs/chapters/ch${m.chapter}/checklist.md`,
  ];

  return plan;
}
