/**
 * `npm run encounters` — THE ENCOUNTER REPORT (S15g Movement Two, ADR-045).
 *
 * Scores EVERY canon map through src/levelkit/pressure.ts and writes
 * docs/ENCOUNTERS.md — one row per map, grouped by class, with the §A9 target
 * BAND and a one-word verdict. It catches the maps the user named: the ones
 * that "look fine but feel annoying or empty". The HARD subset (grace +
 * proximity) is ALSO enforced by the content validator; everything else here
 * is REPORT-ONLY so taste never blocks the build. Re-run after any map change
 * and commit the diff (the report is a tracked artifact for all canon maps).
 */
import { writeFileSync } from 'node:fs';
import { MAPS, CHAR_LEGEND } from '../src/data/maps';
import { TILESET } from '../src/spritegen/tiles';
import {
  pressureReport,
  bandVerdict,
  pressureHardFlags,
  BAND_TARGET,
  PRESSURE_LIMITS,
} from '../src/levelkit/pressure';
import type { PressureReport } from '../src/levelkit/pressure';

// the engine's own tile solidity (matches content-validate.ts exactly)
const solidByName = new Map(TILESET.map((t) => [t.name, t.solid]));
const isSolid = (ch: string): boolean =>
  ch === ':' || ch === 'r' ? false : solidByName.get(CHAR_LEGEND[ch] ?? 'grass_a') === true;

const px = (n: number): string => (n < 0 ? '—' : `${n}px`);

const reports: PressureReport[] = Object.values(MAPS).map((m) => pressureReport(m, isSolid));

const ORDER: PressureReport['klass'][] = ['field', 'dungeon', 'city', 'town', 'village', 'interior'];
const TITLE: Record<PressureReport['klass'], string> = {
  field: 'ROUTES & WILDS (hot — §A9)',
  dungeon: 'DUNGEONS (rising toward the boss — §A9)',
  city: 'CITIES (cool)',
  town: 'TOWNS (cool)',
  village: 'VILLAGES (cool)',
  interior: 'INTERIORS (no ambient pressure)',
};

const lines: string[] = [];
lines.push('# METEOR FALLS — Encounter Pressure Report');
lines.push('');
lines.push('_Generated by `npm run encounters` (S15g Movement Two, ADR-045). One row per canon map._');
lines.push('');
lines.push(`**How to read it.** \`density\` is enemies per 1600×900 screen-equivalent — the §A9 band metric (routes hot, settlements cool, dungeons rising). \`grace\` is the px a doorway gives before the first contact; \`exposure\` the px from the most-exposed rest point to the nearest danger; \`prox\` the px from the nearest spawn to a door/phone/atm/point-trigger. \`touches\` are entrance→exit crossings forced through a dilated spawner (a real fight to traverse); \`side\` are optional off-corridor fights. The HARD subset — grace ≥ ${PRESSURE_LIMITS.MIN_GRACE_PX}px and prox ≥ ${PRESSURE_LIMITS.MIN_PROXIMITY_PX}px — is enforced by the content validator; the rest is taste, reported not gated.`);
lines.push('');

let total = 0;
let cleanHard = 0;
const hardOffenders: Array<{ id: string; flags: string[] }> = [];

for (const k of ORDER) {
  const group = reports.filter((r) => r.klass === k).sort((a, b) => a.id.localeCompare(b.id));
  if (!group.length) continue;
  const [lo, hi] = BAND_TARGET[k];
  lines.push(`## ${TITLE[k]}`);
  lines.push('');
  lines.push(`Target density band: **${lo}–${hi}** enemies/screen.`);
  lines.push('');
  lines.push('| map | tiles | screens | enemies | density | band | grace | exposure | prox | touches | side |');
  lines.push('| --- | ----: | ------: | ------: | ------: | ---- | ----: | -------: | ---: | ------: | ---: |');
  for (const r of group) {
    total += 1;
    const hard = pressureHardFlags(r);
    if (hard.length) hardOffenders.push({ id: r.id, flags: hard });
    else cleanHard += 1;
    const verdict = r.enemyCount === 0 ? '—' : bandVerdict(r);
    const mark = hard.length ? ' ⚠️' : '';
    lines.push(`| ${r.id}${mark} | ${r.tiles} | ${r.screens} | ${r.enemyCount} | ${r.density} | ${verdict} | ${px(r.gracePx)} | ${px(r.restExposurePx)} | ${px(r.proximityPx)} | ${r.unavoidableTouches} | ${r.sidePaths} |`);
  }
  lines.push('');
}

lines.push('## HARD-rule summary');
lines.push('');
lines.push(`${cleanHard}/${total} canon maps clear the hard pressure rules (grace ≥ ${PRESSURE_LIMITS.MIN_GRACE_PX}px, prox ≥ ${PRESSURE_LIMITS.MIN_PROXIMITY_PX}px).`);
lines.push('');
if (hardOffenders.length) {
  lines.push('Maps flagged (each is FIXED or carries a reasoned waiver in `tools/content-validate.ts`):');
  lines.push('');
  for (const o of hardOffenders) for (const f of o.flags) lines.push(`- **${o.id}** — ${f}`);
  lines.push('');
}

writeFileSync('docs/ENCOUNTERS.md', lines.join('\n'), 'utf8');
console.log(`✓ docs/ENCOUNTERS.md — ${total} canon maps scored; ${cleanHard} clear the hard rules, ${hardOffenders.length} flagged`);
for (const o of hardOffenders) console.log(`  ⚠ ${o.id}: ${o.flags.join(' | ')}`);
