/**
 * S8 — Android icon + splash, exported FROM the sprite engine (ADR-002: zero
 * hand-drawn binaries; palette conformance by construction — every pixel is a
 * src/palette.ts index).
 *
 *   npm run art:appart          (vite-node tools/render-appart.ts)
 *
 * What it writes into android/app/src/main/res:
 *  - mipmap-*dpi/ic_launcher.png        24px meteor-over-Otterbrook scene,
 *    integer-upscaled ×2/×3/×4/×6/×8 — every density is the SAME crisp art
 *  - mipmap-*dpi/ic_launcher_round.png  the same art under a circle mask
 *  - mipmap-*dpi/ic_launcher_foreground.png  adaptive layer: 27px scene with
 *    the meteor re-aimed to dead center so launcher masks never crop it
 *  - drawable/splash.xml + drawable-nodpi/splash_art.png  a layer-list splash:
 *    night-sky fill + the 400×225 title scene WITH the logo at ×2, centered
 *    unscaled (gravity=center) — bitmap-stretch distortion can't happen
 *  - values/ic_launcher_background.xml  adaptive/splash backdrop = NIGHT 0
 *
 * Re-run after any palette or title-art change; `npx cap sync` is not needed
 * (res/ is consumed directly by the Gradle build).
 */
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { drawTitleArt, drawLogo, drawAppIcon, scalePixmap } from '../src/spritegen/ui';
import { Pixmap } from '../src/spritegen/pixmap';
import { RAMP, T, px, PALETTE } from '../src/palette';
import { pixmapToPng } from './png';

const RES = join('android', 'app', 'src', 'main', 'res');
const NIGHT_HEX = PALETTE[px(RAMP.NIGHT, 0)]; // #0c0c1c — the sky's top band

function circleMask(pm: Pixmap): Pixmap {
  const out = new Pixmap(pm.w, pm.h);
  const c = (pm.w - 1) / 2;
  const r = pm.w / 2 - 0.5;
  for (let y = 0; y < pm.h; y++) {
    for (let x = 0; x < pm.w; x++) {
      if ((x - c) ** 2 + (y - c) ** 2 <= r * r) out.set(x, y, pm.get(x, y));
    }
  }
  return out;
}

function write(rel: string, bytes: Uint8Array): void {
  const path = join(RES, rel);
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, bytes);
  console.log(`  ${rel}`);
}

console.log('rendering app art from the sprite engine:');

// ---- launcher icons: one 24px scene, integer-upscaled to every density ----
const icon = drawAppIcon(24);
const DENSITIES: Array<[string, number]> = [
  ['mdpi', 2],
  ['hdpi', 3],
  ['xhdpi', 4],
  ['xxhdpi', 6],
  ['xxxhdpi', 8],
];
for (const [dpi, k] of DENSITIES) {
  const scaled = scalePixmap(icon, k);
  write(`mipmap-${dpi}/ic_launcher.png`, pixmapToPng(scaled));
  write(`mipmap-${dpi}/ic_launcher_round.png`, pixmapToPng(circleMask(scaled)));
}

// ---- adaptive foreground: 27px (108dp grid), meteor centered in the safe zone ----
const fg = drawAppIcon(27, true);
for (const [dpi, k] of DENSITIES) {
  write(`mipmap-${dpi}/ic_launcher_foreground.png`, pixmapToPng(scalePixmap(fg, k * 2)));
}

// ---- splash: the real title composition (scene + logo), centered, never stretched ----
const scene = drawTitleArt(400, 225);
const logo = drawLogo();
scene.blit(logo, Math.floor((400 - logo.w) / 2), 26);
write('drawable-nodpi/splash_art.png', pixmapToPng(scalePixmap(scene, 2)));

const SPLASH_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by tools/render-appart.ts (S8) - layer-list so the pixel art
     is centered at native size instead of being stretched as a window
     background; the fill color is palette NIGHT 0, the title sky's top band -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/ic_launcher_background" />
    <item>
        <bitmap
            android:src="@drawable/splash_art"
            android:gravity="center" />
    </item>
</layer-list>
`;
writeFileSync(join(RES, 'drawable', 'splash.xml'), SPLASH_XML);
console.log('  drawable/splash.xml');

const BG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by tools/render-appart.ts (S8): palette NIGHT 0 -->
<resources>
    <color name="ic_launcher_background">${NIGHT_HEX}</color>
</resources>
`;
writeFileSync(join(RES, 'values', 'ic_launcher_background.xml'), BG_XML);
console.log('  values/ic_launcher_background.xml');

// ---- retire the Capacitor template art the layers above replace ----
const STALE = [
  'drawable/splash.png',
  'drawable-land-mdpi/splash.png',
  'drawable-land-hdpi/splash.png',
  'drawable-land-xhdpi/splash.png',
  'drawable-land-xxhdpi/splash.png',
  'drawable-land-xxxhdpi/splash.png',
  'drawable-port-mdpi/splash.png',
  'drawable-port-hdpi/splash.png',
  'drawable-port-xhdpi/splash.png',
  'drawable-port-xxhdpi/splash.png',
  'drawable-port-xxxhdpi/splash.png',
  'drawable/ic_launcher_background.xml',
  'drawable-v24/ic_launcher_foreground.xml',
];
for (const rel of STALE) {
  rmSync(join(RES, rel), { force: true });
}
console.log(`  (removed ${STALE.length} template assets)`);

// sanity: the splash art may only contain palette colors / transparency
let off = 0;
for (let i = 0; i < scene.data.length; i++) {
  const v = scene.data[i];
  if (v !== T && v >= PALETTE.length) off++;
}
if (off > 0) throw new Error(`palette breach: ${off} pixels outside the master palette`);
console.log('done — all art is master-palette indices by construction.');
