/**
 * Android icon + splash exporter.
 *
 * PKG-01 owns the source PNGs in assets/art/icons and assets/art/screens.
 * This step copies those authored package assets into the native Android res
 * tree so Gradle and Capacitor consume the same framing art as the game.
 */
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { PALETTE, RAMP, px } from '../src/palette';

const RES = join('android', 'app', 'src', 'main', 'res');
const ICON = join('assets', 'art', 'icons', 'app_icon.png');
const SPLASH = join('assets', 'art', 'screens', 'splash_art.png');
const NIGHT_HEX = PALETTE[px(RAMP.NIGHT, 0)];

function copy(rel: string, src: string): void {
  const dst = join(RES, rel);
  mkdirSync(dirname(dst), { recursive: true });
  copyFileSync(src, dst);
  console.log(`  ${rel}`);
}

console.log('copying app art from PKG-01 assets:');

const densities = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'];
for (const dpi of densities) {
  copy(`mipmap-${dpi}/ic_launcher.png`, ICON);
  copy(`mipmap-${dpi}/ic_launcher_round.png`, ICON);
  copy(`mipmap-${dpi}/ic_launcher_foreground.png`, ICON);
}

copy('drawable-nodpi/splash_art.png', SPLASH);

const splashXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by tools/render-appart.ts from PKG-01 assets -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/ic_launcher_background" />
    <item>
        <bitmap
            android:src="@drawable/splash_art"
            android:gravity="center" />
    </item>
</layer-list>
`;
const splashXmlPath = join(RES, 'drawable', 'splash.xml');
mkdirSync(dirname(splashXmlPath), { recursive: true });
writeFileSync(splashXmlPath, splashXml);
console.log('  drawable/splash.xml');

const bgXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by tools/render-appart.ts from the title night color -->
<resources>
    <color name="ic_launcher_background">${NIGHT_HEX}</color>
</resources>
`;
const bgXmlPath = join(RES, 'values', 'ic_launcher_background.xml');
mkdirSync(dirname(bgXmlPath), { recursive: true });
writeFileSync(bgXmlPath, bgXml);
console.log('  values/ic_launcher_background.xml');

const stale = [
  'drawable/splash.png',
  'drawable-land-mdpi/splash.png',
  'drawable-land-hdpi/splash.png',
  'drawable-land-xhdpi/splash.png',
  'drawable-land-xxhdpi/splash.png',
  'drawable-land-xxxhdpi/splash.png',
  'drawable-port-mdpi/splash.png',
  'drawable-port-hdpi/splash.png',
  'drawable-port-xhdpi/splash.png',
  'drawable-port-xxhdpi/splash.png',
  'drawable-port-xxxhdpi/splash.png',
  'drawable/ic_launcher_background.xml',
  'drawable-v24/ic_launcher_foreground.xml',
];
for (const rel of stale) rmSync(join(RES, rel), { force: true });
console.log(`  (removed ${stale.length} template assets)`);
console.log('done.');
