/**
 * SCAFFOLD DRAFT — Ch.5 dungeon grammar (site 'the_hedgerow') (generated by `npm run scaffold -- ch5`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch5/checklist.md. Edit freely; re-running overwrites this tree.
 */
import type { DungeonRecipe, DraftMapDef } from '../../../schemas';
import { buildDungeon } from '../../../levelkit/dungeons';

/** the dungeon-grammar draft for "The Hedgerow → the Ducal Crown". (recipe + seed → identical
 *  bytes; Prime Law 2). Promote: hand-art skin, name the rooms, place the boss door. */
export const CH5_DUNGEON_RECIPE: DungeonRecipe = {kind: "dungeon", id: "the_hedgerow", seed: 1059230417, site: "the_hedgerow", encounterBand: "ch5"};

/** build the dungeon draft on demand (the LEVELKIT LAB walks it; bench:map sizes it) */
export const buildCh5Dungeon = (): DraftMapDef => buildDungeon(CH5_DUNGEON_RECIPE);
