/**
 * SCAFFOLD DRAFT — Ch.5 The Grand Duchy of Minimus — draft tree barrel (generated by `npm run scaffold -- ch5`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch5/checklist.md. Edit freely; re-running overwrites this tree.
 */
export { CH5_DUNGEON_RECIPE, buildCh5Dungeon } from './dungeon';
export { CH5_SETTLEMENT_RECIPES, ch5Settlements } from './settlements';
export { CH5_ROSTER } from './roster';
export { CH5_BOSS_DRAFTS } from './boss';
