/**
 * SCAFFOLD DRAFT — Ch.5 forged enemy roster (generated by `npm run scaffold -- ch5`).
 * DRAFTS ARE NOT CONTENT (Prime Law 1, ADR-047): dev-only, excluded from MAPS /
 * the canon manifests / the §B4 sweep. Promotion is a human act — see
 * docs/chapters/ch5/checklist.md. Edit freely; re-running overwrites this tree.
 */
import { FORGED_ROSTERS } from '../../../levelkit/forge/registry';
import type { DraftEnemyDef } from '../../../schemas';

/** the forged Ch.5 roster (deterministic on FIXED_SEED[5] = 1005). Promote:
 *  pick/redraw each face in the Sprite Lab, write §A11 names + death lines, move
 *  the stripped EnemyDefs into src/data/enemies.ts + extend the §A7 manifest. */
export const CH5_ROSTER: readonly DraftEnemyDef[] = FORGED_ROSTERS[5];
